# @Author: Marius Messerschmidt <marius>
# @Date:   08-10-2016 11:10:24
# @Email:  marius.messerschmidt@googlemail.com
# @Last modified by:   marius
# @Last modified time: 08-10-2016 11:10:03
# @License: MIT
language: c
sudo: required # This is not good...

script: ./autogen.sh && ./configure && make && make check

before_install:
  - sudo add-apt-repository ppa:gnome3-team/gnome3 -y
  - sudo add-apt-repository ppa:gnome3-team/gnome3-staging -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgtk-3-dev

after_failure:
  - find . -name "*.log" -exec cat {} +
